sudo: false
language: ruby

rvm:
- ruby-head
- 2.6.0
- 2.5.3
- 2.4.5
- 2.3.8
- 2.2
- 2.1
- 2.0
- jruby-head
- jruby-9.2.5.0

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: 2.2
    - rvm: 2.1
    - rvm: 2.0
